"""empty message

Revision ID: 5976455f9cd6
Revises: ffb4cf367c26
Create Date: 2019-08-04 21:15:48.313099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5976455f9cd6'
down_revision = 'ffb4cf367c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('is_editable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'is_editable')
    # ### end Alembic commands ###
